# SPDX-FileCopyrightText: 🄯 2019-2021 Peter J. Mello <admin@petermello.net>
#
# SPDX-License-Identifier: CC0-1.0
---
github: RogueScholar
open_collective: peter-mello
ko_fi: roguescholar
liberapay: RogueScholar
issuehunt: roguescholar
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
...
