# SPDX-FileCopyrightText: 🄯 2019-2021 Peter J. Mello <admin@petermello.net>
#
# SPDX-License-Identifier: CC0-1.0
---
enabled: true
exclude: []
auto: false
remote_files: []

pull_requests: true
request_review:
  origin: author
  forked: owner

comments: true
statuses: true
labels:
  - pullassigner-ignore
ignore_labels:
  - restyled-ignore
...
